<WhiteSquare>:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20,]
<Button>:
    background_color: 0.2, 0.6, 0.86, 1  # Set the background color of the button
    color: 1, 1, 1, 1  # Set the text color of the button
    font_size: 16
    size_hint: None, None
    size: 300, 40